### ISSUE TITLE
Why the weekday type (Meetup)?

### ISSUE THREAD

**Issue by bcc32** [exercism/xocaml#133]
Core has `Day_of_week.t`.  Why is there a separate type for the input to `meetup_day`?

**Comment by dvberkel** [comment]
@bcc32 good question. I can only guess, because @stevejb71 provided the implementation, but it is something I would do to.

The reason for me would be not being intimately familiar with all the details of `Core`. When I solve a 'problem', I often just implement the tools that I need at the spot, instead of searching for the tool that I know I need in the standard library.

**Comment by stevejb71** [comment]
I wanted to keep the interface independent of Core. Batteries has a date module as well, which someone might want to choose.

**Comment by bcc32** [comment]
I suppose that's fair, although judging from other exercises, e.g., grade-school, Core seems to be the "officially supported" stdlib replacement (`val to_map : school -> string list Int.Map.t`).

**Comment by stevejb71** [comment]
Four other exercises do open it (as they use Map which I don't think such a simple definition in the standard library). For the others, users can potentially use other stdlibs without changing the .mli file (though AFAIK none have so far!).

**Comment by bcc32** [comment]
I mean, Batteries has a map module as well?  I guess I'm just not really understanding the reasoning behind endorsing the Core Map.t as the "official" one but not the Day_of_week.t type?

I don't have super strong feelings about this, I'm just a bit puzzled.

**Comment by stevejb71** [comment]
Without Core, defining a map looks like Map.Make(Int32) (or something similar).
This doesn't look very beginner friendly.

**Comment by dvberkel** [comment]
@bcc32 nobody is saying that one thing over the other is "official". The `example.ml` are nothing more than examples, one way to implement a solution. The are there to show that a exercise is possible, not to dictate doctrine, nor to show the only right way.

A user can choose how to solve an exercise on her own, choosing her own tools.

Having said that, there could be a pedagogical reason to use one library over the other, but in my opinion this should be reflected in the exercise it self, not in the implementation.

**Comment by bcc32** [comment]
@dvberkel I think I wasn't being sufficiently clear.  I'm not talking about the example solutions at all.

I'm talking about requiring the user to return a value of type `Core.Std.Map.t`, which is done in several exercises, which forces the user to at least use Core for some part of those exercises.

What I don't understand is why it wouldn't be possible for a user to simply use the Batteries Date module in their code with the appropriate conversion from the Core `Day_of_week.t` type, e.g.:

```ocaml
let meetup_day schedule weekday ~year ~month =
  let weekday = batteries_day_of weekday in
  ...
```

This is already what I (and at least a couple others) do to use Core with the `weekday` type.

**Comment by dvberkel** [comment]
@bcc32 Sorry for misunderstanding your point.

I do not think there is a conscience decision made to require `Core.Std.Map.t` over Batteries Date module. It just grew organically.

I think is is possible to have done it the way you are suggesting. And in fact it may be even better.

If we were to adopt your situation, we should investigate if it would break solutions already provided by users.
