### ISSUE TITLE
dominoes tests too lenient, Some [(1, 2)] passes every test that expects Some

### ISSUE THREAD

**Issue by petertseng** [exercism/xocaml#139]
The function that unconditionally returns `Some [(1, 2)]` passes 7/12 tests (all of them that expect a Some); the only tests that fail are those tests that are expecting a `None`

This implies that two properties aren't being checked:

1. The front and back of the chain match
2. The dominoes in the solution are the same as the dominoes in the input.

**Comment by stevejb71** [comment]
Thanks for your help here, Peter
