### ISSUE TITLE
Make Hamming conform to official definition

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xocaml#15]
From issue https://github.com/exercism/exercism.io/issues/1867

> Wikipedia says the Hamming distance is not defined for strings of different length.
>
> I am not saying the problems cannot be different, but for such a well-defined concept it would make sense to stick to one definition, especially when the READMEs provide so little information about what is expected from the implementation.

Let's clean this up so that we're using the official definition.

**Comment by bcc32** [comment]
Bump.  I haven't gotten any feedback on my PR so I'm not sure if it's problematic or just that no one's seen it yet.

**Comment by kytrinyx** [comment]
@bcc32 I think this fell between the cracks! So sorry about that.

**Comment by bcc32** [comment]
@kytrinyx No worries!  :)

**Comment by kytrinyx** [comment]
I've pinged @tmcgilchrist on the PR, and also put out a call on Twitter for more people with an interest in and knowledge of OCaml. It would be lovely to have enough eyes on this that we don't lose track of things for months at a time!

**Comment by kytrinyx** [comment]
Apparently we might get an extra pair of eyes on this over the weekend. Fingers crossed (and sorry it's taking so long).

**Comment by dvberkel** [comment]
@bcc32 sorry for the long delay. I reviewed your PR just now and it seems good to me

**Comment by kytrinyx** [comment]
Closed by #41
