### ISSUE TITLE
Exercises don't compile without Core.Std

### ISSUE THREAD

**Issue by jkrmr** [exercism/xocaml#196]
Hi! 👋 

I notice all instances of `open Core.Std` were changed to `open Core` in https://github.com/exercism/xocaml/pull/185.

This seems to have broken the exercises, unless I'm using the wrong version of OCaml or Core? I might be overlooking something else—I'm pretty new to OCaml.

Here's the output I'm seeing from running `make` on a freshly fetched OCaml exercise:

With `open Core`:

```
hello-world master % make
+ ocamlfind ocamlc -c -w A-4-33-40-41-42-43-34-44 -strict-sequence -g -bin-annot -short-paths -thread -package oUnit -package core -ppx 'ppx-jane -as-ppx' -
o test.cmo test.ml                                                                                                                                         
File "test.ml", line 7, characters 50-66:
Error: Unbound value String.to_string
Command exited with code 2.
make: *** [test.native] Error 10
```

With `open Core.Std`:

```
hello-world master % make
F
==============================================================================
Error: Hello World tests:0:Say Hi!.

File "/Users/jkrmr/Projects/exercism/ocaml/hello-world/_build/oUnit-Hello World tests-jkrmr-mbp.local#01.log", line 2, characters 1-1:
Error: Hello World tests:0:Say Hi! (in the log).

Raised at file "src/oUnitAssert.ml", line 45, characters 2-27
Called from file "src/oUnitRunner.ml", line 46, characters 13-26

expected: Hello, World! but got: Change me
------------------------------------------------------------------------------
Ran: 1 tests in: 0.11 seconds.
FAILED: Cases: 1 Tried: 1 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
make: *** [test] Error 1
```

Versions:

```
hello-world master % ocaml --version
The OCaml toplevel, version 4.04.1
```

```
core               113.33.02+4.03  Industrial strength alternative to OCaml's standard library
core_bench         113.33.00+4.03  Benchmarking library
core_extended      113.33.00+4.03  Extra components that are not as closely vetted or as stable as Core
core_kernel        113.33.02+4.03  Industrial strength alternative to OCaml's standard library
```

I haven't been able to find any documentation around `Core.Std` being deprecated in favor of `Core`, but I do notice the project's README [uses the latter](https://github.com/janestreet/core). 

At the same time I'm still seeing many instances of the former:

From the [installation instructions](https://github.com/realworldocaml/book/wiki/Installation-Instructions) [linked-to by exercism](http://exercism.io/languages/ocaml/installing): 

> Build OCaml 4.01 or later using OPAM

> If you want to use Core as your primary standard library, then you should open the Core.Std module by default, which you can do by appending the following to the end of your .ocamlinit.
> ```
> open Core.Std
> ```

**Comment by stevejb71** [comment]
Everything should compile under 4.04.0 (our CI build uses that). I've not had time to try the later version yet. 

You'll need to run ```opam switch 4.04.0``` in your shell. 

Let me know if that fixes it.

**Comment by stevejb71** [comment]
I saw the build failing under 4.04.1 on my local machine (though for a different reason to you - mine was missing corebuild). I cleaned it out and reinstalled, it worked.
