### ISSUE TITLE
Implement OCaml exercises

### ISSUE THREAD

**Issue by tmcgilchrist** [exercism/xocaml#22]
* [ ] bob
* [ ] word-count
* [ ] anagram
* [ ] beer-song
* [ ] nucleotide-count
* [ ] rna-transcription
* [ ] point-mutations
* [ ] phone-number
* [ ] etl
* [ ] grade-school
* [ ] leap
* [ ] meetup
* [ ] space-age
* [ ] grains
* [ ] gigasecond
* [ ] triangle
* [ ] scrabble-score
* [ ] roman-numerals
* [ ] binary
* [ ] prime-factors
* [ ] raindrops
* [ ] allergies
* [ ] strain
* [ ] atbash-cipher
* [ ] accumulate
* [ ] nth-prime
* [ ] palindrome-products
* [ ] sum-of-multiples
* [ ] bank-account
* [ ] minesweeper
* [ ] parallel-letter-frequency
* [ ] zipper
* [ ] sieve
* [ ] pythagorean-triplet
* [ ] difference-of-squares
* [ ] largest-series-product
* [ ] queen-attack
* [ ] saddle-points
* [ ] ocr-numbers
* [ ] pascals-triangle
* [ ] say
* [ ] crypto-square
* [ ] trinary
* [ ] simple-cipher
* [ ] octal
* [ ] luhn
* [ ] pig-latin
* [ ] series
* [ ] secret-handshake
* [ ] linked-list
* [ ] wordy
* [ ] hexadecimal
* [ ] kindergarden-garden
* [ ] binary-search-tree
* [ ] matrix
* [ ] robot

**Comment by kytrinyx** [comment]
This is totally undocumented, but there is now a "todo" key in the API endpoint for each track: http://x.exercism.io/tracks/ocaml

**Comment by tmcgilchrist** [comment]
That's much better, I'll close this then.
