### ISSUE TITLE
Bob example does not compile

### ISSUE THREAD

**Issue by NobbZ** [exercism/xocaml#24]
I tried to learn OCaml the hard way, by doing the exercises.

Since I got some error messages when trying to compile my own stuff, I just copied over the example. Trying to compile it yields the following error:

```plain
$ make
+ ocamlfind ocamldep -syntax camlp4o -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core -modules bob.mli > bob.mli.depends
File "bob.mli", line 1, characters 10-13:
Parse error: [semi] expected after [sig_item] (in [interf])
File "bob.mli", line 1:
Error: Error while running external preprocessor
Command line: camlp4 '-I' '/usr/lib/ocaml/camlp4' '-I' '/home/norbert/.opam/system/lib/type_conv' '-I' '/usr/lib/ocaml' '-I' '/usr/lib/ocaml' '-I' '/home/norbert/.opam/system/lib/bin_prot' '-I' '/home/norbert/.opam/system/lib/bin_prot' '-I' '/home/norbert/.opam/system/lib/sexplib' '-I' '/home/norbert/.opam/system/lib/sexplib' '-I' '/home/norbert/.opam/system/lib/comparelib' '-I' '/home/norbert/.opam/system/lib/comparelib' '-I' '/home/norbert/.opam/system/lib/fieldslib' '-I' '/home/norbert/.opam/system/lib/fieldslib' '-I' '/home/norbert/.opam/system/lib/variantslib' '-I' '/home/norbert/.opam/system/lib/variantslib' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'pa_type_conv.cma' 'unix.cma' 'bigarray.cma' 'bin_prot.cma' 'pa_bin_prot.cma' 'sexplib.cma' 'pa_sexp_conv.cma' 'comparelib.cma' 'pa_compare.cma' 'fieldslib.cma' 'pa_fields_conv.cma' 'variantslib.cma' 'pa_variants_conv.cma'  'bob.mli' > /tmp/ocamlpp1ae013

Command exited with code 2.
make: *** [test.native] Fehler 10
```

My env:

```plain
$ ocaml -version
The OCaml toplevel, version 4.02.1

$ opam --version
1.2.2

$ uname -a
Linux norbert-tuxedo 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pminten** [comment]
I've tried to reproduce this with 4.02.1 but it compiles normally.

The message is suspicious though. If you look at 
https://github.com/exercism/xocaml/blob/master/bob/bob.mli there are no 
characters 10-13 on line 1. Do you have the same bob.mli file as is in 
the repo?

**Comment by NobbZ** [comment]
As I told you, I've tried the example. I took the code from `example.ml` and pasted it into bob.mli.

So the errormessage does see some error there:

```plain
open Core.Std
          ^^^
```

At leat if I counted right.

**Comment by pminten** [comment]
Ah wait, into the mli, not into the ml. Read completely past that. The bob.mli is an interface file (think C header). If you copy example.ml to bob.ml and use bob.mli from the repo it should work.

Norbert Melzer <notifications@github.com> schreef op 12 augustus 2015 18:59:58 CEST:
>As I told you, I've tried the example. I took the code from
>`example.ml` and pasted it into bob.mli.
>
>So the errormessage does see some error there:
>
>```plain
>open Core.Std
>          ^^^
>```
>
>At leat if I counted right.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/xocaml/issues/24#issuecomment-130370104

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by NobbZ** [comment]
Now it works after I modified makefile slightly:

I needed to change the invoked command in `test.native` rule as follows:

```Makefile
test.native: *.ml *.mli
	@corebuild -quiet test.native -pkg oUnit
```

Perhaps this needs to be done elsewhere?

**Comment by NobbZ** [comment]
Just took a look into the current `Makefile`, the rule there is already like mine altered one. It seems as if I had an old `Makefile` lurking around, my first encounter of exercism was January or February, so thats about the age of the `Makefile`.

**Comment by kytrinyx** [comment]
Hm, yeah. If you delete the file and fetch the exercise again, you should get the updated version.

**Comment by tmcgilchrist** [comment]
@NobbZ did @kytrinyx's instructions fix the issue?

**Comment by NobbZ** [comment]
I have never tested and since I needed to reinstall my system from scratch in the meantime I won't have the opportunity to do that.

Anyway, I think we can consider this one fixed, so I close the issue.

**Comment by jkrmr** [comment]
I'm still seeing this, with an updated Makefile (I deleted the bob directory and re-fetched):

```
+ ocamlfind ocamldep -syntax camlp4o -package oUnit -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core -modules test.ml > test.ml.depends
ocamlfind: Package `bin_prot.syntax' not found
Command exited with code 2.
make: *** [test.native] Error 10
```

```
bob master % ocaml -version
The OCaml toplevel, version 4.02.3
```

```shell
CAML_LD_LIBRARY_PATH="/Users/jkrmr/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs"
OPAMUTF8MSGS="1"
PERL5LIB="/Users/jkrmr/.opam/system/lib/perl5:"
OCAML_TOPLEVEL_PATH="/Users/jkrmr/.opam/system/lib/toplevel"
```

**Comment by tmcgilchrist** [comment]
Curious, it's saying that the package `bin_prot` isn't installed which is a dependency of `core`.

I assume that you've got the `core` package installed. `opam list` will show you which packages are installed, it it's not installed do `opam install core` or perhaps just reinstall core e.g. `opam  reinstall core`.

Let me know how you go with that.

**Comment by jkrmr** [comment]
Hmm no dice. But very curious indeed. I'll poke around with it some more.

```
bob master % opam list | ag bin_prot
bin_prot             113.24.00  A binary protocol generator
pa_bin_prot          113.00.01  A binary protocol generator
ppx_bin_prot         113.24.00  Generation of bin_prot readers and writers from

bob master % opam reinstall core
The following actions will be performed:
  ↻  recompile core 113.24.00

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[core] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
⊘  removed   core.113.24.00
Processing  2/2: [core: make]
∗  installed core.113.24.00
Done.


bob master % make clean
rm -rf _build

bob master % make
+ ocamlfind ocamldep -syntax camlp4o -package oUnit -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core -modules test.ml > test.ml.depends
ocamlfind: Package `bin_prot.syntax' not found
Command exited with code 2.
make: *** [test.native] Error 10
```

**Comment by jkrmr** [comment]
@tmcgilchrist I just got this working. 

Steps taken to remedy:

1. Uninstall ocaml and opam using Homebrew
2. Following the [installation instructions for Real World OCaml][instructions], installed opam using homebrew

  i. Uninstalled the ocaml homebrew installs as a dependency of opam
  ii. Installed ocaml using opam using `opam init --comp 4.02.3`
3. Completed the remaining steps in the [instructions][]



[instructions]: https://github.com/realworldocaml/book/wiki/Installation-Instructions

**Comment by tmcgilchrist** [comment]
Interesting. I'm sure I installed open via brew at one point then have
updated the ocaml version as new versions were released.

I'll have a go from scratch this evening. Sounds like we need to be more
specific with our install instructions. Thanks for persevering
