### ISSUE TITLE
Add .merlin

### ISSUE THREAD

**Issue by ismaelga** [exercism/xocaml#25]
I use vim with [merlin](https://github.com/the-lambda-church/merlin) and I have to add a .merlin file to make it work in all the exercises.

Is it ok to make a PR to add this file on all the exercises?

**Comment by kytrinyx** [comment]
Yeah, I think that's fine. I'll make sure that dotfiles get detected and served properly.

**Comment by kytrinyx** [comment]
Update: I've added support for dotfiles in the API.

**Comment by tmcgilchrist** [comment]
Merlin seems to be widely accepted in OCaml, I'm in favour of adding it. (Plus I use it myself in Emacs)

**Comment by ismaelga** [comment]
I will try to arrange some time this weekend to do this

**Comment by tmcgilchrist** [comment]
bump @ismaelga

**Comment by ismaelga** [comment]
@tmcgilchrist I will send a PR today. Thanks for the bump :smiley_cat:

**Comment by ismaelga** [comment]
@tmcgilchrist What do you think about adding `PKG findlib` on .merlin? Is it wide used?

**Comment by tmcgilchrist** [comment]
Done.
