### ISSUE TITLE
Add say exercise to the ocaml track 

### ISSUE THREAD

**Issue by stevejb71** [exercism/xocaml#63]
It is on the F# track and looks to be a good intermediate exercise. 

http://exercism.io/exercises/fsharp/say/readme

I'm available to do this if it helps.

**Comment by dvberkel** [comment]
@stevejb71 it would be wonderful if you could add the say exercise to the OCaml track!

Have you seen the documentation on [porting an exercise to an other language](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track)?

Please reach out if you need any help.

**Comment by stevejb71** [comment]
I've submitted a PR with the exercise in. I would be interested in your feedback.

**Comment by dvberkel** [comment]
@stevejb71 Great! I will take look immediately.

**Comment by dvberkel** [comment]
Looks good. I have on suggestion that would improve readability, otherwise this is awesome.

**Comment by dvberkel** [comment]
@stevejb71 Thanks for porting the say exercise.

And welcome aboard! It is great to see you as an exercism member
