### ISSUE TITLE
Travis build does not compile or run the tests 

### ISSUE THREAD

**Issue by stevejb71** [exercism/xocaml#65]
As a contributor, I would appreciate a CI build being run on my PR.

**Comment by dvberkel** [comment]
Hi @stevejb71 this is a great idea. I will do some research how this could be achieved

**Comment by stevejb71** [comment]
Thanks. If I get time this week I'll take a look too: I'll post on here so we don't duplicate effort.

**Comment by dvberkel** [comment]
I started [a discussion](https://github.com/exercism/discussions/issues/79) to get other people involved in the general idea.

**Comment by dvberkel** [comment]
The [ruby language track](https://github.com/exercism/xruby) has a nice solution for the same problem. I am going will try to mimic it.

**Comment by dvberkel** [comment]
I have made some progress. See pull request #66
