### ISSUE TITLE
Stop ignoring exercises in tests

### ISSUE THREAD

**Issue by dvberkel** [exercism/xocaml#67]
Since pull-request #66 continuous integration runs almost all the tests in the exercises.

The following exercises are ignored. See `IGNOREDIRS` in [Makefile](https://github.com/exercism/xocaml/blob/master/Makefile) for current list

* [ ] prime-factors
* [ ] word-count
* [ ] zipper

We should integrate tests for these exercises into our continuous integration.

**Comment by dvberkel** [comment]
Below are links to the latest Travis CI build that encountered the problematic exercises

* [word-count](https://travis-ci.org/exercism/xocaml/builds/164895381)
* [zipper](https://travis-ci.org/exercism/xocaml/builds/164897086)

**Comment by dvberkel** [comment]
The problem with prime-factors exercise is that it relies on a `Big_int` module.

**Comment by stevejb71** [comment]
I'll take a look (should have some time over this weekend).

**Comment by stevejb71** [comment]
I've opened a PR to upgrade to the latest compiler. If that can be merged I will get on with this one.

**Comment by stevejb71** [comment]
Might also be a good idea to set compiler warnings as errors in the build. It would help to keep the publicly exposed files clean.

**Comment by dvberkel** [comment]
I merged #75
