### ISSUE TITLE
Write an ocaml test generator from canonical data 

### ISSUE THREAD

**Issue by stevejb71** [exercism/xocaml#86]
This would make it easier to keep the ocaml tests in sync with the canonical test data.

**Comment by dvberkel** [comment]
I very much like this idea. I thought about it before, and seeing your recent style of creating test it doesn't seem that hard.

The only thing that will probably be hard is the distinction between "happy" and "error" paths. Sometimes the canonical data differentiates between the two cases by returning `-1` for error cases.

**Comment by stevejb71** [comment]
More than half the exercises can now be covered by the test generator. 
There are some exercises which it won't cover (list-ops for example which requires functions as parameters), but taking it further would be past the point of diminishing returns, at least for the OCaml stream.
So closing this issue.
